#!/usr/bin/env bash

sudo -v

if [ -d "$HOME/.nvm" ]; then
    export NVM_DIR="$HOME/.nvm"

    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    (
        cd "$NVM_DIR"
        git fetch --tags origin
        git checkout $(git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1))
    ) && \. "$NVM_DIR/nvm.sh"

    nvm install --lts
    nvm use --lts
    nvm alias default node
    nvm install --reinstall-packages-from=default --latest-npm 'lts/*'

    nvm cache clear
fi

if which distrobox &>/dev/null; then
    distrobox upgrade -a
    sudo -v
fi

if which npm &>/dev/null; then
    npm update -g
    sudo -v
fi

if which snap &>/dev/null; then
    sudo snap refresh
    sudo -v
fi

if which flatpak &>/dev/null; then
    flatpak update -y
    sudo -v
fi

if which apt &>/dev/null; then
    sudo apt update && sudo apt upgrade -y
    sudo -v
fi

if which yay &>/dev/null; then
    yay
    sudo -v
fi

if which yum &>/dev/null; then
    sudo yum -y update
    sudo -v
fi

if which deno &>/dev/null; then
    deno upgrade
    sudo -v
fi

if which dnf &>/dev/null; then
    sudo dnf upgrade --refresh -y
    sudo -v
fi

if which go &>/dev/null; then
    go install github.com/showwin/speedtest-go@latest
    go install github.com/a-h/templ/cmd/templ@latest
    go install github.com/air-verse/air@latest
    sudo -v
fi
