#!/usr/bin/bash

# https://github.com/trimstray/the-book-of-secret-knowledge?tab=readme-ov-file#domain-resolve

echo -en "Enter the domain / adress: "

read -r _input

_curl_base="curl --request GET"
_timeout="15"

_input_ip=$($_curl_base -ks -m "$_timeout" "https://dns.google.com/resolve?name=${_input}&type=A" | jq '.Answer[0].data' | tr -d "\"" 2>/dev/null)

if [[ -z "$_input_ip" ]] || [[ "$_input_ip" == "null" ]]; then

    echo -en "Unsuccessful domain name resolution.\\n"

else

    echo -en "$_input > $_input_ip\\n"

fi
