#!/usr/bin/bash

path="$(readlink -f -- "$0" | sed 's/fzfSearch//')scripts"
file="$(
    find "${path}" -maxdepth 3 -type f | sed 's/^.*scripts//' |
        fzf \
            --color=dark \
            --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:#44475a,hl+:#ffaf5f \
            --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7
)"

if [ "${file}" ]; then
    bash -e "${path}${file}"
fi
