#!/usr/bin/bash

read -r -p "Are you sure? [y/N] " response
case "$response" in
    [y])
        ;;
    *)
        echo "exiting"
        exit
        ;;
esac

docker stop "$(docker ps -a -q)" > /dev/null 2>&1 &&
docker rm "$(docker ps -a -q)" > /dev/null 2>&1 &&

echo
echo "all containers stopped and removed"
