#!/usr/bin/env bash

file_name=$(find . -type f | fzf --prompt="Select a file: ")

if [ -z "$file_name" ]; then
    echo "No file selected."
    exit 1
fi

mime_type=$(file --mime-type -b "$file_name")
file_info=$(file "$file_name")

case "$mime_type" in
text/plain) ;;
image/*)
    exiftool "$file_name"
    echo "---"
    ;;
audio/* | video/*)
    mediainfo "$file_name"
    echo "---"
    ;;
application/pdf)
    pdfinfo "$file_name"
    echo "---"
    ;;
*)
    echo "No specific action for MIME type: $mime_type"
    echo "---"
    ;;
esac

echo "$file_name"
echo "> $file_info"
