#!/usr/bin/bash

passowrd=$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 24; echo)

echo "$passowrd" | tr -d '[:space:]' | xclip -sel clip

echo "Password copied to clipboard"
