#!/usr/bin/bash

read -r -p "Are you sure? [y/N] " response
case "$response" in
    [y])
        ;;
    *)
        echo "exiting"
        exit
        ;;
esac

# rename space to underscore
for f in *\ *; do mv "$f" "${f// /_}"; done

echo "files renamed"
